<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComarcasSeeder extends Seeder
{
/**
 * Run the database seeds.
 *
 * @return void
 */
    public function run()
    {
        $init = [
            0 => [ 'tribunal_id' => 6,'nome' => 'Fortaleza', 'key' => bcrypt('Fortaleza')],
            1 => [ 'tribunal_id' => 6,'nome' => 'Caucaia', 'key' => bcrypt('Caucaia')],
            2 => [ 'tribunal_id' => 6,'nome' => 'Juazeiro do Norte', 'key' => bcrypt('Juazeiro do Norte')],
            3 => [ 'tribunal_id' => 6,'nome' => 'Maracanaú', 'key' => bcrypt('Maracanaú')],
            4 => [ 'tribunal_id' => 6,'nome' => 'Sobral', 'key' => bcrypt('Sobral')],
            5 => [ 'tribunal_id' => 6,'nome' => 'Crato', 'key' => bcrypt('Crato')],
            6 => [ 'tribunal_id' => 6,'nome' => 'Itapipoca', 'key' => bcrypt('Itapipoca')],
            7 => [ 'tribunal_id' => 6,'nome' => 'Maranguape', 'key' => bcrypt('Maranguape')],
            8 => [ 'tribunal_id' => 6,'nome' => 'Iguatu', 'key' => bcrypt('Iguatu')],
            9 => [ 'tribunal_id' => 6,'nome' => 'Quixadá', 'key' => bcrypt('Quixadá')],
            10 => [ 'tribunal_id' => 6,'nome' => 'Cascavel', 'key' => bcrypt('Cascavel')],
            11 => [ 'tribunal_id' => 6,'nome' => 'Pacatuba', 'key' => bcrypt('Pacatuba')],
            12 => [ 'tribunal_id' => 6,'nome' => 'Quixeramobim', 'key' => bcrypt('Quixeramobim')],
            13 => [ 'tribunal_id' => 6,'nome' => 'Aquiraz', 'key' => bcrypt('Aquiraz')],
            14 => [ 'tribunal_id' => 6,'nome' => 'Russas', 'key' => bcrypt('Russas')],
            15 => [ 'tribunal_id' => 6,'nome' => 'Canindé', 'key' => bcrypt('Canindé')],
            16 => [ 'tribunal_id' => 6,'nome' => 'Tianguá', 'key' => bcrypt('Tianguá')],
            17 => [ 'tribunal_id' => 6,'nome' => 'Aracati', 'key' => bcrypt('Aracati')],
            18 => [ 'tribunal_id' => 6,'nome' => 'Crateús', 'key' => bcrypt('Crateús')],
            19 => [ 'tribunal_id' => 6,'nome' => 'Pacajus', 'key' => bcrypt('Pacajus')],
            20 => [ 'tribunal_id' => 6,'nome' => 'Horizonte', 'key' => bcrypt('Horizonte')],
            21 => [ 'tribunal_id' => 6,'nome' => 'Icó', 'key' => bcrypt('Icó')],
            22 => [ 'tribunal_id' => 6,'nome' => 'Camocim', 'key' => bcrypt('Camocim')],
            23 => [ 'tribunal_id' => 6,'nome' => 'Acaraú', 'key' => bcrypt('Acaraú')],
            24 => [ 'tribunal_id' => 6,'nome' => 'Viçosa do Ceará', 'key' => bcrypt('Viçosa do Ceará')],
            25 => [ 'tribunal_id' => 6,'nome' => 'Barbalha', 'key' => bcrypt('Barbalha')],
            26 => [ 'tribunal_id' => 6,'nome' => 'Morada Nova', 'key' => bcrypt('Morada Nova')],
            27 => [ 'tribunal_id' => 6,'nome' => 'Limoeiro do Norte', 'key' => bcrypt('Limoeiro do Norte')],
            28 => [ 'tribunal_id' => 6,'nome' => 'Tauá', 'key' => bcrypt('Tauá')],
            29 => [ 'tribunal_id' => 6,'nome' => 'Trairi', 'key' => bcrypt('Trairi')],
            30 => [ 'tribunal_id' => 6,'nome' => 'Granja', 'key' => bcrypt('Granja')],
            31 => [ 'tribunal_id' => 6,'nome' => 'Eusébio', 'key' => bcrypt('Eusébio')],
            32 => [ 'tribunal_id' => 6,'nome' => 'Acopiara', 'key' => bcrypt('Acopiara')],
            33 => [ 'tribunal_id' => 6,'nome' => 'Boa Viagem', 'key' => bcrypt('Boa Viagem')],
            34 => [ 'tribunal_id' => 6,'nome' => 'Beberibe', 'key' => bcrypt('Beberibe')],
            35 => [ 'tribunal_id' => 6,'nome' => 'Itapajé', 'key' => bcrypt('Itapajé')],
            36 => [ 'tribunal_id' => 6,'nome' => 'Brejo Santo', 'key' => bcrypt('Brejo Santo')],
            37 => [ 'tribunal_id' => 6,'nome' => 'São Gonçalo do Amarante', 'key' => bcrypt('São Gonçalo do Amarante')],
            38 => [ 'tribunal_id' => 6,'nome' => 'Mauriti', 'key' => bcrypt('Mauriti')],
            39 => [ 'tribunal_id' => 6,'nome' => 'São Benedito', 'key' => bcrypt('São Benedito')],
            40 => [ 'tribunal_id' => 6,'nome' => 'Amontada', 'key' => bcrypt('Amontada')],
            41 => [ 'tribunal_id' => 6,'nome' => 'Mombaça', 'key' => bcrypt('Mombaça')],
            42 => [ 'tribunal_id' => 6,'nome' => 'Santa Quitéria', 'key' => bcrypt('Santa Quitéria')],
            43 => [ 'tribunal_id' => 6,'nome' => 'Pedra Branca', 'key' => bcrypt('Pedra Branca')],
            44 => [ 'tribunal_id' => 6,'nome' => 'Itarema', 'key' => bcrypt('Itarema')],
            45 => [ 'tribunal_id' => 6,'nome' => 'Ipu', 'key' => bcrypt('Ipu')],
            46 => [ 'tribunal_id' => 6,'nome' => 'Várzea Alegre', 'key' => bcrypt('Várzea Alegre')],
            47 => [ 'tribunal_id' => 6,'nome' => 'Guaraciaba do Norte', 'key' => bcrypt('Guaraciaba do Norte')],
            48 => [ 'tribunal_id' => 6,'nome' => 'Massapê', 'key' => bcrypt('Massapê')],
            49 => [ 'tribunal_id' => 6,'nome' => 'Itaitinga', 'key' => bcrypt('Itaitinga')],
            50 => [ 'tribunal_id' => 6,'nome' => 'Ipueiras', 'key' => bcrypt('Ipueiras')],
            51 => [ 'tribunal_id' => 6,'nome' => 'Pentecoste', 'key' => bcrypt('Pentecoste')],
            52 => [ 'tribunal_id' => 6,'nome' => 'Baturité', 'key' => bcrypt('Baturité')],
            53 => [ 'tribunal_id' => 6,'nome' => 'Missão Velha', 'key' => bcrypt('Missão Velha')],
            54 => [ 'tribunal_id' => 6,'nome' => 'Paracuru', 'key' => bcrypt('Paracuru')],
            55 => [ 'tribunal_id' => 6,'nome' => 'Ubajara', 'key' => bcrypt('Ubajara')],
            56 => [ 'tribunal_id' => 6,'nome' => 'Jaguaribe', 'key' => bcrypt('Jaguaribe')],
            57 => [ 'tribunal_id' => 6,'nome' => 'Jaguaruana', 'key' => bcrypt('Jaguaruana')],
            58 => [ 'tribunal_id' => 6,'nome' => 'Paraipaba', 'key' => bcrypt('Paraipaba')],
            59 => [ 'tribunal_id' => 6,'nome' => 'Bela Cruz', 'key' => bcrypt('Bela Cruz')],
            60 => [ 'tribunal_id' => 6,'nome' => 'Santana do Acaraú', 'key' => bcrypt('Santana do Acaraú')],
            61 => [ 'tribunal_id' => 6,'nome' => 'Nova Russas', 'key' => bcrypt('Nova Russas')],
            62 => [ 'tribunal_id' => 6,'nome' => 'Tabuleiro do Norte', 'key' => bcrypt('Tabuleiro do Norte')],
            63 => [ 'tribunal_id' => 6,'nome' => 'Lavras da Mangabeira', 'key' => bcrypt('Lavras da Mangabeira')],
            64 => [ 'tribunal_id' => 6,'nome' => 'Parambu', 'key' => bcrypt('Parambu')],
            65 => [ 'tribunal_id' => 6,'nome' => 'Redenção', 'key' => bcrypt('Redenção')],
            66 => [ 'tribunal_id' => 6,'nome' => 'Novo Oriente', 'key' => bcrypt('Novo Oriente')],
            67 => [ 'tribunal_id' => 6,'nome' => 'Marco', 'key' => bcrypt('Marco')],
            68 => [ 'tribunal_id' => 6,'nome' => 'Campos Sales', 'key' => bcrypt('Campos Sales')],
            69 => [ 'tribunal_id' => 6,'nome' => 'Milagres', 'key' => bcrypt('Milagres')],
            70 => [ 'tribunal_id' => 6,'nome' => 'Jardim', 'key' => bcrypt('Jardim')],
            71 => [ 'tribunal_id' => 6,'nome' => 'Caririaçu', 'key' => bcrypt('Caririaçu')],
            72 => [ 'tribunal_id' => 6,'nome' => 'Aracoiaba', 'key' => bcrypt('Aracoiaba')],
            73 => [ 'tribunal_id' => 6,'nome' => 'Guaiúba', 'key' => bcrypt('Guaiúba')],
            74 => [ 'tribunal_id' => 6,'nome' => 'Tamboril', 'key' => bcrypt('Tamboril')],
            75 => [ 'tribunal_id' => 6,'nome' => 'Independência', 'key' => bcrypt('Independência')],
            76 => [ 'tribunal_id' => 6,'nome' => 'Ocara', 'key' => bcrypt('Ocara')],
            77 => [ 'tribunal_id' => 6,'nome' => 'Cedro', 'key' => bcrypt('Cedro')],
            78 => [ 'tribunal_id' => 6,'nome' => 'Senador Pompeu', 'key' => bcrypt('Senador Pompeu')],
            79 => [ 'tribunal_id' => 6,'nome' => 'Ibiapina', 'key' => bcrypt('Ibiapina')],
            80 => [ 'tribunal_id' => 6,'nome' => 'Cruz', 'key' => bcrypt('Cruz')],
            81 => [ 'tribunal_id' => 6,'nome' => 'Jucás', 'key' => bcrypt('Jucás')],
            82 => [ 'tribunal_id' => 6,'nome' => 'Forquilha', 'key' => bcrypt('Forquilha')],
            83 => [ 'tribunal_id' => 6,'nome' => 'Aurora', 'key' => bcrypt('Aurora')],
            84 => [ 'tribunal_id' => 6,'nome' => 'Irauçuba', 'key' => bcrypt('Irauçuba')],
            85 => [ 'tribunal_id' => 6,'nome' => 'Assaré', 'key' => bcrypt('Assaré')],
            86 => [ 'tribunal_id' => 6,'nome' => 'Coreaú', 'key' => bcrypt('Coreaú')],
            87 => [ 'tribunal_id' => 6,'nome' => 'Caridade', 'key' => bcrypt('Caridade')],
            88 => [ 'tribunal_id' => 6,'nome' => 'Barro', 'key' => bcrypt('Barro')],
            89 => [ 'tribunal_id' => 6,'nome' => 'Morrinhos', 'key' => bcrypt('Morrinhos')],
            90 => [ 'tribunal_id' => 6,'nome' => 'Barreira', 'key' => bcrypt('Barreira')],
            91 => [ 'tribunal_id' => 6,'nome' => 'Quixeré', 'key' => bcrypt('Quixeré')],
            92 => [ 'tribunal_id' => 6,'nome' => 'Uruburetama', 'key' => bcrypt('Uruburetama')],
            93 => [ 'tribunal_id' => 6,'nome' => 'Itatira', 'key' => bcrypt('Itatira')],
            94 => [ 'tribunal_id' => 6,'nome' => 'Araripe', 'key' => bcrypt('Araripe')],
            95 => [ 'tribunal_id' => 6,'nome' => 'Orós', 'key' => bcrypt('Orós')],
            96 => [ 'tribunal_id' => 6,'nome' => 'Quiterianópolis', 'key' => bcrypt('Quiterianópolis')],
            97 => [ 'tribunal_id' => 6,'nome' => 'Catarina', 'key' => bcrypt('Catarina')],
            98 => [ 'tribunal_id' => 6,'nome' => 'Pindoretama', 'key' => bcrypt('Pindoretama')],
            99 => [ 'tribunal_id' => 6,'nome' => 'Itapiúna', 'key' => bcrypt('Itapiúna')],
            100 => [ 'tribunal_id' => 6,'nome' => 'Jericoacoara', 'key' => bcrypt('Jericoacoara')],
            101 => [ 'tribunal_id' => 6,'nome' => 'Chorozinho', 'key' => bcrypt('Chorozinho')],
            102 => [ 'tribunal_id' => 6,'nome' => 'Icapuí', 'key' => bcrypt('Icapuí')],
            103 => [ 'tribunal_id' => 6,'nome' => 'Hidrolândia', 'key' => bcrypt('Hidrolândia')],
            104 => [ 'tribunal_id' => 6,'nome' => 'Madalena', 'key' => bcrypt('Madalena')],
            105 => [ 'tribunal_id' => 6,'nome' => 'Umirim', 'key' => bcrypt('Umirim')],
            106 => [ 'tribunal_id' => 6,'nome' => 'Tejuçuoca', 'key' => bcrypt('Tejuçuoca')],
            107 => [ 'tribunal_id' => 6,'nome' => 'Farias Brito', 'key' => bcrypt('Farias Brito')],
            108 => [ 'tribunal_id' => 6,'nome' => 'Cariús', 'key' => bcrypt('Cariús')],
            109 => [ 'tribunal_id' => 6,'nome' => 'Varjota', 'key' => bcrypt('Varjota')],
            110 => [ 'tribunal_id' => 6,'nome' => 'Cariré', 'key' => bcrypt('Cariré')],
            111 => [ 'tribunal_id' => 6,'nome' => 'Solonópole', 'key' => bcrypt('Solonópole')],
            112 => [ 'tribunal_id' => 6,'nome' => 'Banabuiú', 'key' => bcrypt('Banabuiú')],
            113 => [ 'tribunal_id' => 6,'nome' => 'Reriutaba', 'key' => bcrypt('Reriutaba')],
            114 => [ 'tribunal_id' => 6,'nome' => 'Croatá', 'key' => bcrypt('Croatá')],
            115 => [ 'tribunal_id' => 6,'nome' => 'Jaguaretama', 'key' => bcrypt('Jaguaretama')],
            116 => [ 'tribunal_id' => 6,'nome' => 'Capistrano', 'key' => bcrypt('Capistrano')],
            117 => [ 'tribunal_id' => 6,'nome' => 'Carnaubal', 'key' => bcrypt('Carnaubal')],
            118 => [ 'tribunal_id' => 6,'nome' => 'Santana do Cariri', 'key' => bcrypt('Santana do Cariri')],
            119 => [ 'tribunal_id' => 6,'nome' => 'Aiuaba', 'key' => bcrypt('Aiuaba')],
            120 => [ 'tribunal_id' => 6,'nome' => 'Monsenhor Tabosa', 'key' => bcrypt('Monsenhor Tabosa')],
            121 => [ 'tribunal_id' => 6,'nome' => 'Piquet Caneiro', 'key' => bcrypt('Piquet Caneiro')],
            122 => [ 'tribunal_id' => 6,'nome' => 'Fortim', 'key' => bcrypt('Fortim')],
            123 => [ 'tribunal_id' => 6,'nome' => 'Salitre', 'key' => bcrypt('Salitre')],
            124 => [ 'tribunal_id' => 6,'nome' => 'Tururu', 'key' => bcrypt('Tururu')],
            125 => [ 'tribunal_id' => 6,'nome' => 'Pereiro', 'key' => bcrypt('Pereiro')],
            126 => [ 'tribunal_id' => 6,'nome' => 'Quixelô', 'key' => bcrypt('Quixelô')],
            127 => [ 'tribunal_id' => 6,'nome' => 'Alto Santo', 'key' => bcrypt('Alto Santo')],
            128 => [ 'tribunal_id' => 6,'nome' => 'Nova Olinda', 'key' => bcrypt('Nova Olinda')],
            129 => [ 'tribunal_id' => 6,'nome' => 'Saboeiro', 'key' => bcrypt('Saboeiro')],
            130 => [ 'tribunal_id' => 6,'nome' => 'Meruoca', 'key' => bcrypt('Meruoca')],
            131 => [ 'tribunal_id' => 6,'nome' => 'Acarape', 'key' => bcrypt('Acarape')],
            132 => [ 'tribunal_id' => 6,'nome' => 'Barroquinha', 'key' => bcrypt('Barroquinha')],
            133 => [ 'tribunal_id' => 6,'nome' => 'Apuiarés', 'key' => bcrypt('Apuiarés')],
            134 => [ 'tribunal_id' => 6,'nome' => 'Porteiras', 'key' => bcrypt('Porteiras')],
            135 => [ 'tribunal_id' => 6,'nome' => 'Mucambo', 'key' => bcrypt('Mucambo')],
            136 => [ 'tribunal_id' => 6,'nome' => 'Graça', 'key' => bcrypt('Graça')],
            137 => [ 'tribunal_id' => 6,'nome' => 'Iracema', 'key' => bcrypt('Iracema')],
            138 => [ 'tribunal_id' => 6,'nome' => 'Frecheirinha', 'key' => bcrypt('Frecheirinha')],
            139 => [ 'tribunal_id' => 6,'nome' => 'Uruoca', 'key' => bcrypt('Uruoca')],
            140 => [ 'tribunal_id' => 6,'nome' => 'Miraíma', 'key' => bcrypt('Miraíma')],
            141 => [ 'tribunal_id' => 6,'nome' => 'Choró', 'key' => bcrypt('Choró')],
            142 => [ 'tribunal_id' => 6,'nome' => 'Palmácia', 'key' => bcrypt('Palmácia')],
            143 => [ 'tribunal_id' => 6,'nome' => 'Ibaretama', 'key' => bcrypt('Ibaretama')],
            144 => [ 'tribunal_id' => 6,'nome' => 'Milhã', 'key' => bcrypt('Milhã')],
            145 => [ 'tribunal_id' => 6,'nome' => 'Chaval', 'key' => bcrypt('Chaval')],
            146 => [ 'tribunal_id' => 6,'nome' => 'São Luís do Curu', 'key' => bcrypt('São Luís do Curu')],
            147 => [ 'tribunal_id' => 6,'nome' => 'Ibicuitinga', 'key' => bcrypt('Ibicuitinga')],
            148 => [ 'tribunal_id' => 6,'nome' => 'Ipaumirim', 'key' => bcrypt('Ipaumirim')],
            149 => [ 'tribunal_id' => 6,'nome' => 'Poranga', 'key' => bcrypt('Poranga')],
            150 => [ 'tribunal_id' => 6,'nome' => 'Pacoti', 'key' => bcrypt('Pacoti')],
            151 => [ 'tribunal_id' => 6,'nome' => 'Paramoti', 'key' => bcrypt('Paramoti')],
            152 => [ 'tribunal_id' => 6,'nome' => 'Abaiara', 'key' => bcrypt('Abaiara')],
            153 => [ 'tribunal_id' => 6,'nome' => 'Alcântaras', 'key' => bcrypt('Alcântaras')],
            154 => [ 'tribunal_id' => 6,'nome' => 'Aratuba', 'key' => bcrypt('Aratuba')],
            155 => [ 'tribunal_id' => 6,'nome' => 'Ipaporanga', 'key' => bcrypt('Ipaporanga')],
            156 => [ 'tribunal_id' => 6,'nome' => 'Jaguaribara', 'key' => bcrypt('Jaguaribara')],
            157 => [ 'tribunal_id' => 6,'nome' => 'Martinópole', 'key' => bcrypt('Martinópole')],
            158 => [ 'tribunal_id' => 6,'nome' => 'Groaíras', 'key' => bcrypt('Groaíras')],
            159 => [ 'tribunal_id' => 6,'nome' => 'Potengi', 'key' => bcrypt('Potengi')],
            160 => [ 'tribunal_id' => 6,'nome' => 'Mulungu', 'key' => bcrypt('Mulungu')],
            161 => [ 'tribunal_id' => 6,'nome' => 'Pires Ferreira', 'key' => bcrypt('Pires Ferreira')],
            162 => [ 'tribunal_id' => 6,'nome' => 'Ararendá', 'key' => bcrypt('Ararendá')],
            163 => [ 'tribunal_id' => 6,'nome' => 'Catunda', 'key' => bcrypt('Catunda')],
            164 => [ 'tribunal_id' => 6,'nome' => 'Irapuan Pinheiro', 'key' => bcrypt('Irapuan Pinheiro')],
            165 => [ 'tribunal_id' => 6,'nome' => 'Palhano', 'key' => bcrypt('Palhano')],
            166 => [ 'tribunal_id' => 6,'nome' => 'Penaforte', 'key' => bcrypt('Penaforte')],
            167 => [ 'tribunal_id' => 6,'nome' => 'Moraújo', 'key' => bcrypt('Moraújo')],
            168 => [ 'tribunal_id' => 6,'nome' => 'Tarrafas', 'key' => bcrypt('Tarrafas')],
            169 => [ 'tribunal_id' => 6,'nome' => 'Jati', 'key' => bcrypt('Jati')],
            170 => [ 'tribunal_id' => 6,'nome' => 'Itaiçaba', 'key' => bcrypt('Itaiçaba')],
            171 => [ 'tribunal_id' => 6,'nome' => 'Arneiroz', 'key' => bcrypt('Arneiroz')],
            172 => [ 'tribunal_id' => 6,'nome' => 'General Sampaio', 'key' => bcrypt('General Sampaio')],
            173 => [ 'tribunal_id' => 6,'nome' => 'Senador Sá', 'key' => bcrypt('Senador Sá')],
            174 => [ 'tribunal_id' => 6,'nome' => 'Umari', 'key' => bcrypt('Umari')],
            175 => [ 'tribunal_id' => 6,'nome' => 'Altaneira', 'key' => bcrypt('Altaneira')],
            176 => [ 'tribunal_id' => 6,'nome' => 'São João do Jaguaribe', 'key' => bcrypt('São João do Jaguaribe')],
            177 => [ 'tribunal_id' => 6,'nome' => 'Antonina do Norte', 'key' => bcrypt('Antonina do Norte')],
            178 => [ 'tribunal_id' => 6,'nome' => 'Ereré', 'key' => bcrypt('Ereré')],
            179 => [ 'tribunal_id' => 6,'nome' => 'Pacujá', 'key' => bcrypt('Pacujá')],
            180 => [ 'tribunal_id' => 6,'nome' => 'Potiretama', 'key' => bcrypt('Potiretama')],
            181 => [ 'tribunal_id' => 6,'nome' => 'Baixio', 'key' => bcrypt('Baixio')],
            182 => [ 'tribunal_id' => 6,'nome' => 'Guaramiranga', 'key' => bcrypt('Guaramiranga')],
            183 => [ 'tribunal_id' => 6,'nome' => 'Granjeiro', 'key' => bcrypt('Granjeiro')],

        ];
        DB::table('comarcas')->insert($init);
    }
}
