<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VarasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $init = [
            0 => [ 'comarca_id' => 33,'nome' => '1ª Vara – Acopiara', 'key' => bcrypt('1ª Vara – Acopiara')],
            1 => [ 'comarca_id' => 33,'nome' => '2ª Vara – Acopiara', 'key' => bcrypt('2ª Vara – Acopiara')],
            2 => [ 'comarca_id' => 73,'nome' => 'Vara Única de Aracoiaba', 'key' => bcrypt('Vara Única de Aracoiaba')],
            3 => [ 'comarca_id' => 18,'nome' => 'Vara Única Criminal de Aracati', 'key' => bcrypt('Vara Única Criminal de Aracati')],
            4 => [ 'comarca_id' => 18,'nome' => '1ª Vara Cível de Aracati', 'key' => bcrypt('1ª Vara Cível de Aracati')],
            5 => [ 'comarca_id' => 18,'nome' => '2ª Vara Cível de Aracati', 'key' => bcrypt('2ª Vara Cível de Aracati')],
            6 => [ 'comarca_id' => 61,'nome' => '1ª Vara – Acaraú', 'key' => bcrypt('1ª Vara – Acaraú')],
            7 => [ 'comarca_id' => 61,'nome' => '2ª Vara – Acaraú', 'key' => bcrypt('2ª Vara – Acaraú')],
            8 => [ 'comarca_id' => 84,'nome' => 'Vara Única - Aurora', 'key' => bcrypt('Vara Única - Aurora')],
            9 => [ 'comarca_id' => 132,'nome' => 'Vara Única - Acarape', 'key' => bcrypt('Vara Única - Acarape')],
            10 => [ 'comarca_id' => 128,'nome' => 'Vara Única – Alto Santo', 'key' => bcrypt('Vara Única – Alto Santo')],
            11 => [ 'comarca_id' => 120,'nome' => 'Vara Única – Aiuaba', 'key' => bcrypt('Vara Única – Aiuaba')],
            12 => [ 'comarca_id' => 154,'nome' => 'Vara Única – Alcantaras', 'key' => bcrypt('Vara Única – Alcantaras')],
            13 => [ 'comarca_id' => 176,'nome' => 'Vara Única – Altaneira', 'key' => bcrypt('Vara Única – Altaneira')],
            14 => [ 'comarca_id' => 153,'nome' => 'Vara Única – Abaiara', 'key' => bcrypt('Vara Única – Abaiara')],
            15 => [ 'comarca_id' => 41,'nome' => 'Vara Única – Amontada', 'key' => bcrypt('Vara Única – Amontada')],
            16 => [ 'comarca_id' => 155,'nome' => 'Vara Única – Aratuba', 'key' => bcrypt('Vara Única – Aratuba')],
            17 => [ 'comarca_id' => 163,'nome' => 'Vara Única – Ararendá', 'key' => bcrypt('Vara Única – Ararendá')],
            18 => [ 'comarca_id' => 134,'nome' => 'Vara Única - Apuiarés', 'key' => bcrypt('Vara Única - Apuiarés')],
            19 => [ 'comarca_id' => 14,'nome' => 'Vara Única Criminal de Aquiraz', 'key' => bcrypt('Vara Única Criminal de Aquiraz')],
            20 => [ 'comarca_id' => 14,'nome' => '1ª Vara Cível de Aquiraz', 'key' => bcrypt('1ª Vara Cível de Aquiraz')],
            21 => [ 'comarca_id' => 14,'nome' => '2ª Vara Cível de Aquiraz', 'key' => bcrypt('2ª Vara Cível de Aquiraz')],
            22 => [ 'comarca_id' => 86,'nome' => 'Vara Única de Assaré', 'key' => bcrypt('Vara Única de Assaré')],
            23 => [ 'comarca_id' => 34,'nome' => '1ª Vara – Boa Viagem', 'key' => bcrypt('1ª Vara – Boa Viagem')],
            24 => [ 'comarca_id' => 26,'nome' => 'Vara Única Criminal de Barbalha', 'key' => bcrypt('Vara Única Criminal de Barbalha')],
            25 => [ 'comarca_id' => 53,'nome' => 'Vara Única Criminal de Baturité', 'key' => bcrypt('Vara Única Criminal de Baturité')],
            26 => [ 'comarca_id' => 37,'nome' => '1ª Vara – Brejo santo', 'key' => bcrypt('1ª Vara – Brejo santo')],
            27 => [ 'comarca_id' => 26,'nome' => '1ª Vara Cível de Barbalha', 'key' => bcrypt('1ª Vara Cível de Barbalha')],
            28 => [ 'comarca_id' => 37,'nome' => '2ª Vara – Brejo Santo', 'key' => bcrypt('2ª Vara – Brejo Santo')],
            29 => [ 'comarca_id' => 34,'nome' => '2ª Vara – Boa Viagem', 'key' => bcrypt('2ª Vara – Boa Viagem')],
            30 => [ 'comarca_id' => 53,'nome' => '1ª Vara Cível de Baturité', 'key' => bcrypt('1ª Vara Cível de Baturité')],
            31 => [ 'comarca_id' => 26,'nome' => '2ª Vara Cível de Barbalha', 'key' => bcrypt('2ª Vara Cível de Barbalha')],
            32 => [ 'comarca_id' => 53,'nome' => '2ª Vara Cível de Baturité', 'key' => bcrypt('2ª Vara Cível de Baturité')],
            33 => [ 'comarca_id' => 60,'nome' => 'Vara Única de Bela Cruz', 'key' => bcrypt('Vara Única de Bela Cruz')],
            34 => [ 'comarca_id' => 91,'nome' => 'Vara Única de Barreira', 'key' => bcrypt('Vara Única de Barreira')],
            35 => [ 'comarca_id' => 133,'nome' => 'Vara Única de Barroquinha', 'key' => bcrypt('Vara Única de Barroquinha')],
            36 => [ 'comarca_id' => 89,'nome' => 'Vara Única de Barro', 'key' => bcrypt('Vara Única de Barro')],
            37 => [ 'comarca_id' => 35,'nome' => '1ª Vara de Beberibe', 'key' => bcrypt('1ª Vara de Beberibe')],
            38 => [ 'comarca_id' => 35,'nome' => '2ª Vara de Beberibe', 'key' => bcrypt('2ª Vara de Beberibe')],
            39 => [ 'comarca_id' => 15,'nome' => 'Vara Única Criminal de Canindé', 'key' => bcrypt('Vara Única Criminal de Canindé')],
            40 => [ 'comarca_id' => 15,'nome' => '1ª Vara Cível de Canindé', 'key' => bcrypt('1ª Vara Cível de Canindé')],
            41 => [ 'comarca_id' => 15,'nome' => '2ª Vara Cível de Canindé', 'key' => bcrypt('2ª Vara Cível de Canindé')],
            42 => [ 'comarca_id' => 69,'nome' => 'Vara Única de Campos Sales', 'key' => bcrypt('Vara Única de Campos Sales')],
            43 => [ 'comarca_id' => 115,'nome' => 'Vara Única de Croatá', 'key' => bcrypt('Vara Única de Croatá')],
            44 => [ 'comarca_id' => 11,'nome' => '1ª Vara de Cascavel', 'key' => bcrypt('1ª Vara de Cascavel')],
            45 => [ 'comarca_id' => 23,'nome' => '1ª Vara de Camocim', 'key' => bcrypt('1ª Vara de Camocim')],
            46 => [ 'comarca_id' => 2,'nome' => '1ª Vara de Família e Sucessões de Caucaia', 'key' => bcrypt('1ª Vara de Família e Sucessões de Caucaia')],
            47 => [ 'comarca_id' => 2,'nome' => '1ª Unidade do Juizado Especial Cível e Criminal de Caucaia', 'key' => bcrypt('1ª Unidade do Juizado Especial Cível e Criminal de Caucaia')],
            48 => [ 'comarca_id' => 2,'nome' => '2ª Unidade do Juizado Especial Cível e Criminal de Caucaia', 'key' => bcrypt('2ª Unidade do Juizado Especial Cível e Criminal de Caucaia')],
            49 => [ 'comarca_id' => 6,'nome' => '1ª Vara Cível do Crato', 'key' => bcrypt('1ª Vara Cível do Crato')],
            50 => [ 'comarca_id' => 2,'nome' => '1ª Vara Cível de Caucaia', 'key' => bcrypt('1ª Vara Cível de Caucaia')],
            51 => [ 'comarca_id' => 2,'nome' => '2ª Vara Cível de Caucaia', 'key' => bcrypt('2ª Vara Cível de Caucaia')],
            52 => [ 'comarca_id' => 2,'nome' => '3ª Vara Cível de Caucaia', 'key' => bcrypt('3ª Vara Cível de Caucaia')],
            53 => [ 'comarca_id' => 11,'nome' => '2ª Vara de Cascavel', 'key' => bcrypt('2ª Vara de Cascavel')],
            54 => [ 'comarca_id' => 2,'nome' => '2ª Vara de Família de Caucaia', 'key' => bcrypt('2ª Vara de Família de Caucaia')],
            55 => [ 'comarca_id' => 2,'nome' => '2ª Vara Criminal de Caucaia', 'key' => bcrypt('2ª Vara Criminal de Caucaia')],
            56 => [ 'comarca_id' => 2,'nome' => '3ª Vara Criminal de Caucaia', 'key' => bcrypt('3ª Vara Criminal de Caucaia')],
            57 => [ 'comarca_id' => 6,'nome' => '1ª Vara Criminal do Crato', 'key' => bcrypt('1ª Vara Criminal do Crato')],
            58 => [ 'comarca_id' => 6,'nome' => '2ª Vara Criminal do Crato', 'key' => bcrypt('2ª Vara Criminal do Crato')],
            59 => [ 'comarca_id' => 6,'nome' => '2ª Vara Cível do Crato', 'key' => bcrypt('2ª Vara Cível do Crato')],
            60 => [ 'comarca_id' => 23,'nome' => '2ª vara de Camocim', 'key' => bcrypt('2ª vara de Camocim')],
            61 => [ 'comarca_id' => 19,'nome' => 'Vara Única Criminal de Crateús', 'key' => bcrypt('Vara Única Criminal de Crateús')],
            62 => [ 'comarca_id' => 19,'nome' => '1ª Vara Cível de Crateús', 'key' => bcrypt('1ª Vara Cível de Crateús')],
            63 => [ 'comarca_id' => 19,'nome' => '2ª Vara Cível de Crateús', 'key' => bcrypt('2ª Vara Cível de Crateús')],
            64 => [ 'comarca_id' => 2,'nome' => '3ª Vara Criminal de Caucaia', 'key' => bcrypt('3ª Vara Criminal de Caucaia')],
            65 => [ 'comarca_id' => 2,'nome' => '4ª Vara Criminal de Caucaia', 'key' => bcrypt('4ª Vara Criminal de Caucaia')],
            66 => [ 'comarca_id' => 117,'nome' => 'Vara Única de Capistrano', 'key' => bcrypt('Vara Única de Capistrano')],
            67 => [ 'comarca_id' => 2,'nome' => 'Vara Única do Júri de Caucaia', 'key' => bcrypt('Vara Única do Júri de Caucaia')],
            68 => [ 'comarca_id' => 111,'nome' => 'Vara Única de Cariré', 'key' => bcrypt('Vara Única de Cariré')],
            69 => [ 'comarca_id' => 81,'nome' => 'Vara Única de Cruz', 'key' => bcrypt('Vara Única de Cruz')],
            70 => [ 'comarca_id' => 118,'nome' => 'Vara Única de Carnaubal', 'key' => bcrypt('Vara Única de Carnaubal')],
            71 => [ 'comarca_id' => 78,'nome' => 'Vara Única de Cedro', 'key' => bcrypt('Vara Única de Cedro')],
            72 => [ 'comarca_id' => 98,'nome' => 'Vara Única de Catarina', 'key' => bcrypt('Vara Única de Catarina')],
            73 => [ 'comarca_id' => 102,'nome' => 'Vara Única de Chorozinho', 'key' => bcrypt('Vara Única de Chorozinho')],
            74 => [ 'comarca_id' => 72,'nome' => 'Vara Única de Caririaçu', 'key' => bcrypt('Vara Única de Caririaçu')],
            75 => [ 'comarca_id' => 146,'nome' => 'Vara Única de Chaval', 'key' => bcrypt('Vara Única de Chaval')],
            76 => [ 'comarca_id' => 6,'nome' => 'Vara Única de Família e Sucessões do Crato', 'key' => bcrypt('Vara Única de Família e Sucessões do Crato')],
            77 => [ 'comarca_id' => 2,'nome' => 'Vara Única da Infância e Juventude de Caucaia', 'key' => bcrypt('Vara Única da Infância e Juventude de Caucaia')],
            78 => [ 'comarca_id' => 87,'nome' => 'Vara Única de Coreaú', 'key' => bcrypt('Vara Única de Coreaú')],
            79 => [ 'comarca_id' => 88,'nome' => 'Vara Única de Caridade', 'key' => bcrypt('Vara Única de Caridade')],
            80 => [ 'comarca_id' => 32,'nome' => 'Vara Única Criminal de Eusébio', 'key' => bcrypt('Vara Única Criminal de Eusébio')],
            81 => [ 'comarca_id' => 32,'nome' => '1ª Vara Cível de Eusébio', 'key' => bcrypt('1ª Vara Cível de Eusébio')],
            82 => [ 'comarca_id' => 32,'nome' => '2ª Vara Cível de Eusébio', 'key' => bcrypt('2ª Vara Cível de Eusébio')],
            83 => [ 'comarca_id' => 178,'nome' => 'Vara Única de Ererê', 'key' => bcrypt('Vara Única de Ererê')],
            84 => [ 'comarca_id' => 1,'nome' => '1ª Vara de Registros Públicos – Fortaleza', 'key' => bcrypt('1ª Vara de Registros Públicos – Fortaleza')],
            85 => [ 'comarca_id' => 1,'nome' => '1ª Vara de Execuções Fiscais – Fortaleza', 'key' => bcrypt('1ª Vara de Execuções Fiscais – Fortaleza')],
            86 => [ 'comarca_id' => 1,'nome' => '1ª Vara de Execução Penal – Fortaleza', 'key' => bcrypt('1ª Vara de Execução Penal – Fortaleza')],
            87 => [ 'comarca_id' => 1,'nome' => '1ª Vara Criminal – Fortaleza', 'key' => bcrypt('1ª Vara Criminal – Fortaleza')],
            88 => [ 'comarca_id' => 1,'nome' => '1ª Vara Cível – Fortaleza', 'key' => bcrypt('1ª Vara Cível – Fortaleza')],
            89 => [ 'comarca_id' => 1,'nome' => '1ª Vara de Delitos de Tráfico de Drogas – Fortaleza', 'key' => bcrypt('1ª Vara de Delitos de Tráfico de Drogas – Fortaleza')],
            90 => [ 'comarca_id' => 1,'nome' => '1ª Vara de Recuperação de Empresas e Falência – Fortaleza', 'key' => bcrypt('1ª Vara de Recuperação de Empresas e Falência – Fortaleza')],
            91 => [ 'comarca_id' => 1,'nome' => '1ª Vara de Familia – Fortaleza', 'key' => bcrypt('1ª Vara de Familia – Fortaleza')],
            92 => [ 'comarca_id' => 1,'nome' => '1ª Vara de Sucessões – Fortaleza', 'key' => bcrypt('1ª Vara de Sucessões – Fortaleza')],
            93 => [ 'comarca_id' => 1,'nome' => '1ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('1ª Vara da Fazenda Pública – Fortaleza')],
            94 => [ 'comarca_id' => 1,'nome' => '1ª Vara do Júri – Fortaleza', 'key' => bcrypt('1ª Vara do Júri – Fortaleza')],
            95 => [ 'comarca_id' => 1,'nome' => '1ª Vara da Infância e Juventude– Fortaleza', 'key' => bcrypt('1ª Vara da Infância e Juventude– Fortaleza')],
            96 => [ 'comarca_id' => 1,'nome' => '2ª Vara de Sucessões – Fortaleza', 'key' => bcrypt('2ª Vara de Sucessões – Fortaleza')],
            97 => [ 'comarca_id' => 1,'nome' => '2ª Vara de Delitos de Tráfico de Drogas – Fortaleza', 'key' => bcrypt('2ª Vara de Delitos de Tráfico de Drogas – Fortaleza')],
            98 => [ 'comarca_id' => 1,'nome' => '2ª Vara de Registros Públicos – Fortaleza', 'key' => bcrypt('2ª Vara de Registros Públicos – Fortaleza')],
            99 => [ 'comarca_id' => 1,'nome' => '2ª Vara de Recuperação de Empresas e Falência – Fortaleza', 'key' => bcrypt('2ª Vara de Recuperação de Empresas e Falência – Fortaleza')],
            100 => [ 'comarca_id' => 1,'nome' => '2ª Vara Cível – Fortaleza', 'key' => bcrypt('2ª Vara Cível – Fortaleza')],
            101 => [ 'comarca_id' => 1,'nome' => '2ª Vara Criminal– Fortaleza', 'key' => bcrypt('2ª Vara Criminal– Fortaleza')],
            102 => [ 'comarca_id' => 1,'nome' => '2ª Vara de Execuções Fiscais – Fortaleza', 'key' => bcrypt('2ª Vara de Execuções Fiscais – Fortaleza')],
            103 => [ 'comarca_id' => 1,'nome' => '2ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('2ª Vara da Fazenda Pública – Fortaleza')],
            104 => [ 'comarca_id' => 1,'nome' => '2ª Vara de Família – Fortaleza', 'key' => bcrypt('2ª Vara de Família – Fortaleza')],
            105 => [ 'comarca_id' => 1,'nome' => '2ª Vara do Júri – Fortaleza', 'key' => bcrypt('2ª Vara do Júri – Fortaleza')],
            106 => [ 'comarca_id' => 1,'nome' => '2ª Vara de Execução Penal – Fortaleza', 'key' => bcrypt('2ª Vara de Execução Penal – Fortaleza')],
            107 => [ 'comarca_id' => 1,'nome' => '2ª Vara da Infância e Juventude de Fortaleza', 'key' => bcrypt('2ª Vara da Infância e Juventude de Fortaleza')],
            108 => [ 'comarca_id' => 1,'nome' => '3ª Vara de Delitos de Tráfico de Drogas – Fortaleza', 'key' => bcrypt('3ª Vara de Delitos de Tráfico de Drogas – Fortaleza')],
            109 => [ 'comarca_id' => 1,'nome' => '3ª Vara da Infância e Juventude – Fortaleza', 'key' => bcrypt('3ª Vara da Infância e Juventude – Fortaleza')],
            110 => [ 'comarca_id' => 1,'nome' => '3ª Vara do Júri – Fortaleza', 'key' => bcrypt('3ª Vara do Júri – Fortaleza')],
            111 => [ 'comarca_id' => 1,'nome' => '3ª Vara de Execução Penal – Fortaleza', 'key' => bcrypt('3ª Vara de Execução Penal – Fortaleza')],
            112 => [ 'comarca_id' => 1,'nome' => '3ª Vara de Execuções Fiscais – Fortaleza', 'key' => bcrypt('3ª Vara de Execuções Fiscais – Fortaleza')],
            113 => [ 'comarca_id' => 1,'nome' => '3ª Vara de Sucessões – Fortaleza', 'key' => bcrypt('3ª Vara de Sucessões – Fortaleza')],
            114 => [ 'comarca_id' => 1,'nome' => '3ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('3ª Vara da Fazenda Pública – Fortaleza')],
            115 => [ 'comarca_id' => 1,'nome' => '3ª Vara de Família – Fortaleza', 'key' => bcrypt('3ª Vara de Família – Fortaleza')],
            116 => [ 'comarca_id' => 1,'nome' => '3ª Vara Criminal – Fortaleza', 'key' => bcrypt('3ª Vara Criminal – Fortaleza')],
            117 => [ 'comarca_id' => 1,'nome' => '3ª Vara Cível – Fortaleza', 'key' => bcrypt('3ª Vara Cível – Fortaleza')],
            118 => [ 'comarca_id' => 1,'nome' => '3ª Vara de Execuções Penais– Fortaleza', 'key' => bcrypt('3ª Vara de Execuções Penais– Fortaleza')],
            119 => [ 'comarca_id' => 1,'nome' => '3ª Vara da Infância e Juventude– Fortaleza', 'key' => bcrypt('3ª Vara da Infância e Juventude– Fortaleza')],
            120 => [ 'comarca_id' => 1,'nome' => '4ª Vara de Execuções Penais– Fortaleza', 'key' => bcrypt('4ª Vara de Execuções Penais– Fortaleza')],
            121 => [ 'comarca_id' => 1,'nome' => '4ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('4ª Vara da Fazenda Pública – Fortaleza')],
            122 => [ 'comarca_id' => 1,'nome' => '4ª Vara de Execuções Fiscais – Fortaleza', 'key' => bcrypt('4ª Vara de Execuções Fiscais – Fortaleza')],
            123 => [ 'comarca_id' => 1,'nome' => '4ª Vara de Sucessões – Fortaleza', 'key' => bcrypt('4ª Vara de Sucessões – Fortaleza')],
            124 => [ 'comarca_id' => 1,'nome' => '4ª Vara da Infância e Juventude– Fortaleza', 'key' => bcrypt('4ª Vara da Infância e Juventude– Fortaleza')],
            125 => [ 'comarca_id' => 1,'nome' => '4ª Câmara de Direito Privado – Fortaleza', 'key' => bcrypt('4ª Câmara de Direito Privado – Fortaleza')],
            126 => [ 'comarca_id' => 1,'nome' => '4ª Vara Cível – Fortaleza', 'key' => bcrypt('4ª Vara Cível – Fortaleza')],
            127 => [ 'comarca_id' => 1,'nome' => '4ª Vara do Júri – Fortaleza', 'key' => bcrypt('4ª Vara do Júri – Fortaleza')],
            128 => [ 'comarca_id' => 1,'nome' => '4ª Vara Criminal – Fortaleza', 'key' => bcrypt('4ª Vara Criminal – Fortaleza')],
            129 => [ 'comarca_id' => 1,'nome' => '4ª Vara de Família – Fortaleza', 'key' => bcrypt('4ª Vara de Família – Fortaleza')],
            130 => [ 'comarca_id' => 1,'nome' => '4ª Vara de Delitos de Tráfico de Drogas – Fortaleza', 'key' => bcrypt('4ª Vara de Delitos de Tráfico de Drogas – Fortaleza')],
            131 => [ 'comarca_id' => 1,'nome' => '5ª Vara de Delitos de Tráfico de Drogas – Fortaleza', 'key' => bcrypt('5ª Vara de Delitos de Tráfico de Drogas – Fortaleza')],
            132 => [ 'comarca_id' => 1,'nome' => '5ª Vara de Sucessões – Fortaleza', 'key' => bcrypt('5ª Vara de Sucessões – Fortaleza')],
            133 => [ 'comarca_id' => 1,'nome' => '5ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('5ª Vara da Fazenda Pública – Fortaleza')],
            134 => [ 'comarca_id' => 1,'nome' => '5ª Vara Criminal – Fortaleza', 'key' => bcrypt('5ª Vara Criminal – Fortaleza')],
            135 => [ 'comarca_id' => 1,'nome' => '5ª Vara do Júri – Fortaleza', 'key' => bcrypt('5ª Vara do Júri – Fortaleza')],
            136 => [ 'comarca_id' => 1,'nome' => '5ª Unidade – Juizado Especial Cível - Fortaleza', 'key' => bcrypt('5ª Unidade – Juizado Especial Cível - Fortaleza')],
            137 => [ 'comarca_id' => 1,'nome' => '5ª Vara de Família – Fortaleza', 'key' => bcrypt('5ª Vara de Família – Fortaleza')],
            138 => [ 'comarca_id' => 1,'nome' => '5ª Vara da Infância e Juventude – Fortaleza', 'key' => bcrypt('5ª Vara da Infância e Juventude – Fortaleza')],
            139 => [ 'comarca_id' => 1,'nome' => '5ª Vara de Execuções Fiscais – Fortaleza', 'key' => bcrypt('5ª Vara de Execuções Fiscais – Fortaleza')],
            140 => [ 'comarca_id' => 1,'nome' => '5ª Vara Cível – Fortaleza', 'key' => bcrypt('5ª Vara Cível – Fortaleza')],
            141 => [ 'comarca_id' => 1,'nome' => '1ª Vara Cível – Fortaleza', 'key' => bcrypt('6ª Vara Cível – Fortaleza')],
            142 => [ 'comarca_id' => 1,'nome' => '6ª Vara Criminal – Fortaleza', 'key' => bcrypt('6ª Vara Criminal – Fortaleza')],
            143 => [ 'comarca_id' => 1,'nome' => '6ª Vara de Execuções Fiscais – Fortaleza', 'key' => bcrypt('6ª Vara de Execuções Fiscais – Fortaleza')],
            144 => [ 'comarca_id' => 1,'nome' => '6ª Vara de Família – Fortaleza', 'key' => bcrypt('6ª Vara de Família – Fortaleza')],
            145 => [ 'comarca_id' => 1,'nome' => '6ª Vara da Fazenda Pública', 'key' => bcrypt('6ª Vara da Fazenda Pública')],
            146 => [ 'comarca_id' => 1, 'nome' => '7ª Vara da Fazenda Pública', 'key' => bcrypt('7ª Vara da Fazenda Pública')],
            147 => [ 'comarca_id' => 1, 'nome' => '7ª Vara Criminal – Fortaleza', 'key' => bcrypt('7ª Vara Criminal – Fortaleza')],
            148 => [ 'comarca_id' => 1, 'nome' => '7ª Vara de Família – Fortaleza', 'key' => bcrypt('7ª Vara de Família – Fortaleza')],
            149 => [ 'comarca_id' => 1, 'nome' => '7ª Vara Cível – Fortaleza', 'key' => bcrypt('7ª Vara Cível – Fortaleza')],
            150 => [ 'comarca_id' => 1, 'nome' => '8ª Vara Cível – Fortaleza', 'key' => bcrypt('8ª Vara Cível – Fortaleza')],
            151 => [ 'comarca_id' => 1, 'nome' => '8ª Vara de Família – Fortaleza', 'key' => bcrypt('8ª Vara de Família – Fortaleza')],
            152 => [ 'comarca_id' => 1, 'nome' => '8ª Vara da Fazenda Pública - Fortaleza', 'key' => bcrypt('8ª Vara da Fazenda Pública - Fortaleza')],
            153 => [ 'comarca_id' => 1, 'nome' => '8ª Vara Criminal– Fortaleza', 'key' => bcrypt('8ª Vara Criminal– Fortaleza')],
            154 => [ 'comarca_id' => 1, 'nome' => '9ª Vara Cível – Fortaleza', 'key' => bcrypt('9ª Vara Cível – Fortaleza')],
            155 => [ 'comarca_id' => 1, 'nome' => '9ª Vara da Fazenda Pública - Fortaleza', 'key' => bcrypt('9ª Vara da Fazenda Pública - Fortaleza')],
            156 => [ 'comarca_id' => 1, 'nome' => '9ª Vara Criminal– Fortaleza', 'key' => bcrypt('9ª Vara Criminal– Fortaleza')],
            157 => [ 'comarca_id' => 1, 'nome' => '9ª Vara de Família – Fortaleza', 'key' => bcrypt('9ª Vara de Família – Fortaleza')],
            158 => [ 'comarca_id' => 1, 'nome' => '10ª Vara de Família – Fortaleza', 'key' => bcrypt('10ª Vara de Família – Fortaleza')],
            159 => [ 'comarca_id' => 1, 'nome' => '10ª Vara Criminal – Fortaleza', 'key' => bcrypt('10ª Vara Criminal – Fortaleza')],
            160 => [ 'comarca_id' => 1, 'nome' => '10ª Vara Cível – Fortaleza', 'key' => bcrypt('10ª Vara Cível – Fortaleza')],
            161 => [ 'comarca_id' => 1, 'nome' => '10ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('10ª Vara da Fazenda Pública – Fortaleza')],
            162 => [ 'comarca_id' => 1, 'nome' => '11ª Vara Criminal – Fortaleza', 'key' => bcrypt('11ª Vara Criminal – Fortaleza')],
            163 => [ 'comarca_id' => 1, 'nome' => '11ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('11ª Vara da Fazenda Pública – Fortaleza')],
            164 => [ 'comarca_id' => 1, 'nome' => '11ª Vara Cível – Fortaleza', 'key' => bcrypt('11ª Vara Cível – Fortaleza')],
            165 => [ 'comarca_id' => 1, 'nome' => '11ª Vara de Família – Fortaleza', 'key' => bcrypt('11ª Vara de Família – Fortaleza')],
            166 => [ 'comarca_id' => 1, 'nome' => '12ª Vara Criminal – Fortaleza', 'key' => bcrypt('12ª Vara Criminal – Fortaleza')],
            167 => [ 'comarca_id' => 1, 'nome' => '12ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('12ª Vara da Fazenda Pública – Fortaleza')],
            168 => [ 'comarca_id' => 1, 'nome' => '12ª Vara Cível – Fortaleza', 'key' => bcrypt('12ª Vara Cível – Fortaleza')],
            169 => [ 'comarca_id' => 1, 'nome' => '12ª Vara de Família – Fortaleza', 'key' => bcrypt('12ª Vara de Família – Fortaleza')],
            170 => [ 'comarca_id' => 1, 'nome' => '13ª Vara Criminal – Fortaleza', 'key' => bcrypt('13ª Vara Criminal – Fortaleza')],
            171 => [ 'comarca_id' => 1, 'nome' => '13ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('13ª Vara da Fazenda Pública – Fortaleza')],
            172 => [ 'comarca_id' => 1, 'nome' => '13ª Vara Cível – Fortaleza', 'key' => bcrypt('13ª Vara Cível – Fortaleza')],
            173 => [ 'comarca_id' => 1, 'nome' => '13ª Vara de Família – Fortaleza', 'key' => bcrypt('13ª Vara de Família – Fortaleza')],
            174 => [ 'comarca_id' => 1, 'nome' => '14ª Vara Criminal – Fortaleza', 'key' => bcrypt('14ª Vara Criminal – Fortaleza')],
            175 => [ 'comarca_id' => 1, 'nome' => '14ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('14ª Vara da Fazenda Pública – Fortaleza')],
            176 => [ 'comarca_id' => 1, 'nome' => '14ª Vara Cível – Fortaleza', 'key' => bcrypt('14ª Vara Cível – Fortaleza')],
            177 => [ 'comarca_id' => 1, 'nome' => '14ª Vara de Família – Fortaleza', 'key' => bcrypt('14ª Vara de Família – Fortaleza')],
            178 => [ 'comarca_id' => 1, 'nome' => '15ª Vara Criminal – Fortaleza', 'key' => bcrypt('15ª Vara Criminal – Fortaleza')],
            179 => [ 'comarca_id' => 1, 'nome' => '15ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('15ª Vara da Fazenda Pública – Fortaleza')],
            180 => [ 'comarca_id' => 1, 'nome' => '15ª Vara Cível – Fortaleza', 'key' => bcrypt('15ª Vara Cível – Fortaleza')],
            181 => [ 'comarca_id' => 1, 'nome' => '15ª Vara de Família – Fortaleza', 'key' => bcrypt('15ª Vara de Família – Fortaleza')],
            182 => [ 'comarca_id' => 1, 'nome' => '16ª Vara Criminal – Fortaleza', 'key' => bcrypt('16ª Vara Criminal – Fortaleza')],
            183 => [ 'comarca_id' => 1, 'nome' => '16ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('16ª Vara da Fazenda Pública – Fortaleza')],
            184 => [ 'comarca_id' => 1, 'nome' => '16ª Vara Cível – Fortaleza', 'key' => bcrypt('16ª Vara Cível – Fortaleza')],
            185 => [ 'comarca_id' => 1, 'nome' => '16ª Vara de Família – Fortaleza', 'key' => bcrypt('16ª Vara de Família – Fortaleza')],
            186 => [ 'comarca_id' => 1, 'nome' => '17ª Vara Criminal – Fortaleza', 'key' => bcrypt('17ª Vara Criminal – Fortaleza')],
            187 => [ 'comarca_id' => 1, 'nome' => '17ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('17ª Vara da Fazenda Pública – Fortaleza')],
            188 => [ 'comarca_id' => 1, 'nome' => '17ª Vara Cível – Fortaleza', 'key' => bcrypt('17ª Vara Cível – Fortaleza')],
            189 => [ 'comarca_id' => 1, 'nome' => '17ª Vara de Família – Fortaleza', 'key' => bcrypt('17ª Vara de Família – Fortaleza')],
            190 => [ 'comarca_id' => 1, 'nome' => '18ª Vara Criminal – Fortaleza', 'key' => bcrypt('18ª Vara Criminal – Fortaleza')],
            191 => [ 'comarca_id' => 1, 'nome' => '18ª Vara da Fazenda Pública – Fortaleza', 'key' => bcrypt('18ª Vara da Fazenda Pública – Fortaleza')],
            192 => [ 'comarca_id' => 1, 'nome' => '18ª Vara Cível – Fortaleza', 'key' => bcrypt('18ª Vara Cível – Fortaleza')],
            193 => [ 'comarca_id' => 1, 'nome' => '18ª Vara de Família – Fortaleza', 'key' => bcrypt('18ª Vara de Família – Fortaleza')],
            194 => [ 'comarca_id' => 1, 'nome' => '19ª Vara Cível – Fortaleza', 'key' => bcrypt('19ª Vara Cível – Fortaleza')],
            195 => [ 'comarca_id' => 1, 'nome' => '20ª Vara Cível – Fortaleza', 'key' => bcrypt('20ª Vara Cível – Fortaleza')],
            196 => [ 'comarca_id' => 1, 'nome' => '21ª Vara Cível – Fortaleza', 'key' => bcrypt('21ª Vara Cível – Fortaleza')],
            197 => [ 'comarca_id' => 1, 'nome' => '22ª Vara Cível – Fortaleza', 'key' => bcrypt('22ª Vara Cível – Fortaleza')],
            198 => [ 'comarca_id' => 1, 'nome' => '23ª Vara Cível – Fortaleza', 'key' => bcrypt('23ª Vara Cível – Fortaleza')],
            199 => [ 'comarca_id' => 1, 'nome' => '24ª Vara Cível – Fortaleza', 'key' => bcrypt('24ª Vara Cível – Fortaleza')],
            200 => [ 'comarca_id' => 1, 'nome' => '25ª Vara Cível – Fortaleza', 'key' => bcrypt('25ª Vara Cível – Fortaleza')],
            201 => [ 'comarca_id' => 1, 'nome' => '26ª Vara Cível – Fortaleza', 'key' => bcrypt('26ª Vara Cível – Fortaleza')],
            202 => [ 'comarca_id' => 1, 'nome' => '27ª Vara Cível – Fortaleza', 'key' => bcrypt('27ª Vara Cível – Fortaleza')],
            203 => [ 'comarca_id' => 1, 'nome' => '28ª Vara Cível – Fortaleza', 'key' => bcrypt('28ª Vara Cível – Fortaleza')],
            204 => [ 'comarca_id' => 1, 'nome' => '29ª Vara Cível – Fortaleza', 'key' => bcrypt('29ª Vara Cível – Fortaleza')],
            205 => [ 'comarca_id' => 1, 'nome' => '30ª Vara Cível – Fortaleza', 'key' => bcrypt('30ª Vara Cível – Fortaleza')],
            206 => [ 'comarca_id' => 1, 'nome' => '31ª Vara Cível – Fortaleza', 'key' => bcrypt('31ª Vara Cível – Fortaleza')],
            207 => [ 'comarca_id' => 1, 'nome' => '32ª Vara Cível – Fortaleza', 'key' => bcrypt('32ª Vara Cível – Fortaleza')],
            208 => [ 'comarca_id' => 1, 'nome' => '33ª Vara Cível – Fortaleza', 'key' => bcrypt('33ª Vara Cível – Fortaleza')],
            209 => [ 'comarca_id' => 1, 'nome' => '34ª Vara Cível – Fortaleza', 'key' => bcrypt('34ª Vara Cível – Fortaleza')],
            210 => [ 'comarca_id' => 1, 'nome' => '35ª Vara Cível – Fortaleza', 'key' => bcrypt('35ª Vara Cível – Fortaleza')],
            211 => [ 'comarca_id' => 1, 'nome' => '36ª Vara Cível – Fortaleza', 'key' => bcrypt('36ª Vara Cível – Fortaleza')],
            212 => [ 'comarca_id' => 1, 'nome' => '37ª Vara Cível – Fortaleza', 'key' => bcrypt('37ª Vara Cível – Fortaleza')],
            213 => [ 'comarca_id' => 1, 'nome' => '38ª Vara Cível – Fortaleza', 'key' => bcrypt('38ª Vara Cível – Fortaleza')],
            214 => [ 'comarca_id' => 1, 'nome' => '39ª Vara Cível – Fortaleza', 'key' => bcrypt('39ª Vara Cível – Fortaleza')],
            215 => [ 'comarca_id' => 1, 'nome' => 'Vara de Penas Alternativas - Fortaleza', 'key' => bcrypt('Vara de Penas Alternativas - Fortaleza')],
            216 => [ 'comarca_id' => 1, 'nome' => 'Vara de Delitos de Organizações Criminosas', 'key' => bcrypt('Vara de Delitos de Organizações Criminosas')],
            217 => [ 'comarca_id' => 1, 'nome' => 'Vara Única da Justiça Militar do Ceará', 'key' => bcrypt('Vara Única da Justiça Militar do Ceará')],
            218 => [ 'comarca_id' => 1, 'nome' => 'Vara de Crimes contra a Ordem Tributária de Fortaleza', 'key' => bcrypt('Vara de Crimes contra a Ordem Tributária de Fortaleza')],
            219 => [ 'comarca_id' => 1, 'nome' => 'Vara Única Privativa de Audiências de Custódia - Fortaleza', 'key' => bcrypt('Vara Única Privativa de Audiências de Custódia - Fortaleza')],
            220 => [ 'comarca_id' => 139,'nome' => 'Vara Única – Frecheirinha', 'key' => bcrypt('Vara Única – Frecheirinha')],
            221 => [ 'comarca_id' => 108,'nome' => 'Vara Única – Farias Brito', 'key' => bcrypt('Vara Única – Farias Brito')],
            222 => [ 'comarca_id' => 83,'nome' => 'Vara Única de Forquilha', 'key' => bcrypt('Vara Única de Forquilha')],
            223 => [ 'comarca_id' => 123,'nome' => 'Vara Única de Fortim', 'key' => bcrypt('Vara Única de Fortim')],
            224 => [ 'comarca_id' => 31,'nome' => '1ª Vara de Granja', 'key' => bcrypt('1ª Vara de Granja')],
            225 => [ 'comarca_id' => 31,'nome' => '2ª Vara de Granja', 'key' => bcrypt('2ª Vara de Granja')],
            226 => [ 'comarca_id' => 48,'nome' => 'Vara Única de Guaraciaba do Norte', 'key' => bcrypt('Vara Única de Guaraciaba do Norte')],
            227 => [ 'comarca_id' => 137,'nome' => 'Vara Única de Graça', 'key' => bcrypt('Vara Única de Graça')],
            228 => [ 'comarca_id' => 21,'nome' => '1ª Vara de Horizonte', 'key' => bcrypt('1ª Vara de Horizonte')],
            229 => [ 'comarca_id' => 21,'nome' => '2ª Vara de Horizonte', 'key' => bcrypt('2ª Vara de Horizonte')],
            230 => [ 'comarca_id' => 104,'nome' => 'Vara Única de Hidrolândia', 'key' => bcrypt('Vara Única de Hidrolândia')],
            231 => [ 'comarca_id' => 9,'nome' => '1ª Vara Criminal de Iguatu', 'key' => bcrypt('1ª Vara Criminal de Iguatu')],
            232 => [ 'comarca_id' => 7,'nome' => 'Vara Única Criminal de Itapipoca', 'key' => bcrypt('Vara Única Criminal de Itapipoca')],
            233 => [ 'comarca_id' => 117,'nome' => 'Vara Única de Itapiuna', 'key' => bcrypt('Vara Única de Itapiuna')],
            234 => [ 'comarca_id' => 36,'nome' => '1ª Vara de Itapajé', 'key' => bcrypt('1ª Vara de Itapajé')],
            235 => [ 'comarca_id' => 22,'nome' => '1ª Vara – Icó', 'key' => bcrypt('1ª Vara – Icó')],
            236 => [ 'comarca_id' => 50,'nome' => '1ª Vara de Itaitinga', 'key' => bcrypt('1ª Vara de Itaitinga')],
            237 => [ 'comarca_id' => 22,'nome' => '2ª Vara de Icó', 'key' => bcrypt('2ª Vara de Icó')],
            238 => [ 'comarca_id' => 7,'nome' => '1ª Vara Cível de Itapipoca', 'key' => bcrypt('1ª Vara Cível de Itapipoca')],
            239 => [ 'comarca_id' => 36,'nome' => '2ª Vara de Itapajé', 'key' => bcrypt('2ª Vara de Itapajé')],
            240 => [ 'comarca_id' => 9,'nome' => '1ª Vara Cível de Iguatu', 'key' => bcrypt('1ª Vara Cível de Iguatu')],
            241 => [ 'comarca_id' => 50,'nome' => '2ª Vara de Itaitinga', 'key' => bcrypt('2ª Vara de Itaitinga')],
            242 => [ 'comarca_id' => 7,'nome' => '2ª Vara Cível de Itapipoca', 'key' => bcrypt('2ª Vara Cível de Itapipoca')],
            243 => [ 'comarca_id' => 9,'nome' => '2ª Vara Cível de Iguatu', 'key' => bcrypt('2ª Vara Cível de Iguatu')],
            244 => [ 'comarca_id' => 9,'nome' => '2ª Vara Criminal de Iguatu', 'key' => bcrypt('2ª Vara Criminal de Iguatu')],
            245 => [ 'comarca_id' => 85,'nome' => 'Vara Única de Irauçuba', 'key' => bcrypt('Vara Única de Irauçuba')],
            246 => [ 'comarca_id' => 138,'nome' => 'Vara Única de Iracema', 'key' => bcrypt('Vara Única de Iracema')],
            247 => [ 'comarca_id' => 80,'nome' => 'Vara Única de Ibiapina', 'key' => bcrypt('Vara Única de Ibiapina')],
            248 => [ 'comarca_id' => 149,'nome' => 'Vara Única de Ipaumirim', 'key' => bcrypt('Vara Única de Ipaumirim')],
            249 => [ 'comarca_id' => 76,'nome' => 'Vara Única de Independência', 'key' => bcrypt('Vara Única de Independência')],
            250 => [ 'comarca_id' => 148,'nome' => 'Vara Única de Ibicuitinga', 'key' => bcrypt('Vara Única de Ibicuitinga')],
            251 => [ 'comarca_id' => 46,'nome' => 'Vara Única de Ipu', 'key' => bcrypt('Vara Única de Ipu')],
            252 => [ 'comarca_id' => 51,'nome' => 'Vara Única de Ipueiras', 'key' => bcrypt('Vara Única de Ipueiras')],
            253 => [ 'comarca_id' => 156,'nome' => 'Vara Única de Ipaporanga', 'key' => bcrypt('Vara Única de Ipaporanga')],
            254 => [ 'comarca_id' => 103,'nome' => 'Vara Única de Icapuí', 'key' => bcrypt('Vara Única de Icapuí')],
            255 => [ 'comarca_id' => 94,'nome' => 'Vara Única de Itatira', 'key' => bcrypt('Vara Única de Itatira')],
            256 => [ 'comarca_id' => 45,'nome' => 'Vara Única de Itarema', 'key' => bcrypt('Vara Única de Itarema')],
            257 => [ 'comarca_id' => 3,'nome' => '1ª Vara Cível de Juazeiro do Norte', 'key' => bcrypt('1ª Vara Cível de Juazeiro do Norte')],
            258 => [ 'comarca_id' => 3,'nome' => '1ª Vara de Família de Juazeiro do Norte', 'key' => bcrypt('1ª Vara de Família de Juazeiro do Norte')],
            259 => [ 'comarca_id' => 3,'nome' => '1ª Vara Criminal de Juazeiro do Norte', 'key' => bcrypt('1ª Vara Criminal de Juazeiro do Norte')],
            260 => [ 'comarca_id' => 3,'nome' => '2ª Vara de Família de Juazeiro do Norte', 'key' => bcrypt('2ª Vara de Família de Juazeiro do Norte')],
            261 => [ 'comarca_id' => 3,'nome' => '2ª Vara Criminal de Juazeiro do Norte', 'key' => bcrypt('2ª Vara Criminal de Juazeiro do Norte')],
            262 => [ 'comarca_id' => 3,'nome' => '2ª Vara Cível de Juazeiro do Norte', 'key' => bcrypt('2ª Vara Cível de Juazeiro do Norte')],
            263 => [ 'comarca_id' => 3,'nome' => '3ª Vara Cível de Juazeiro do Norte', 'key' => bcrypt('3ª Vara Cível de Juazeiro do Norte')],
            264 => [ 'comarca_id' => 3,'nome' => '3ª Vara Criminal de Juazeiro do Norte', 'key' => bcrypt('3ª Vara Criminal de Juazeiro do Norte')],
            265 => [ 'comarca_id' => 82,'nome' => 'Vara Única de Jucás', 'key' => bcrypt('Vara Única de Jucás')],
            266 => [ 'comarca_id' => 116,'nome' => 'Vara Única de Jaguaretama', 'key' => bcrypt('Vara Única de Jaguaretama')],
            267 => [ 'comarca_id' => 157,'nome' => 'Vara Única de Jaguaribara', 'key' => bcrypt('Vara Única de Jaguaribara')],
            268 => [ 'comarca_id' => 57,'nome' => 'Vara Única de Jaguaribe', 'key' => bcrypt('Vara Única de Jaguaribe')],
            269 => [ 'comarca_id' => 3,'nome' => 'Vara Única da Infância e Juventude – Juazeiro do Norte', 'key' => bcrypt('Vara Única da Infância e Juventude – Juazeiro do Norte')],
            270 => [ 'comarca_id' => 71,'nome' => 'Vara Única de Jardim', 'key' => bcrypt('Vara Única de Jardim')],
            271 => [ 'comarca_id' => 58,'nome' => 'Vara Única de Jaguaruana', 'key' => bcrypt('Vara Única de Jaguaruana')],
            272 => [ 'comarca_id' => 101,'nome' => 'Vara Única de Jijoca de Jericoacoara', 'key' => bcrypt('Vara Única de Jijoca de Jericoacoara')],
            273 => [ 'comarca_id' => 64,'nome' => 'Vara Única de Lavras da Mangabeira', 'key' => bcrypt('Vara Única de Lavras da Mangabeira')],
            274 => [ 'comarca_id' => 28,'nome' => 'Vara Única Criminal de Limoeiro do Norte', 'key' => bcrypt('Vara Única Criminal de Limoeiro do Norte')],
            275 => [ 'comarca_id' => 28,'nome' => '1ª Vara Cível de Limoeiro do Norte', 'key' => bcrypt('1ª Vara Cível de Limoeiro do Norte')],
            276 => [ 'comarca_id' => 28,'nome' => '2ª Vara Cível de Limoeiro do Norte', 'key' => bcrypt('2ª Vara Cível de Limoeiro do Norte')],
            277 => [ 'comarca_id' => 49,'nome' => '1ª Vara e Diretoria do Fórum de Massapê', 'key' => bcrypt('1ª Vara e Diretoria do Fórum de Massapê')],
            278 => [ 'comarca_id' => 4,'nome' => '1ª Vara de Família e Sucessões – Maracanaú', 'key' => bcrypt('1ª Vara de Família e Sucessões – Maracanaú')],
            279 => [ 'comarca_id' => 4,'nome' => '1ª Vara Criminal de Maracanaú', 'key' => bcrypt('1ª Vara Criminal de Maracanaú')],
            280 => [ 'comarca_id' => 42,'nome' => '1ª Vara – Mombaça', 'key' => bcrypt('1ª Vara – Mombaça')],
            281 => [ 'comarca_id' => 27,'nome' => 'Vara Única Criminal de Morada Nova', 'key' => bcrypt('Vara Única Criminal de Morada Nova')],
            282 => [ 'comarca_id' => 4,'nome' => '1ª Vara Cível de Maracanaú', 'key' => bcrypt('1ª Vara Cível de Maracanaú')],
            283 => [ 'comarca_id' => 8,'nome' => 'Vara Única Criminal de Maranguape', 'key' => bcrypt('Vara Única Criminal de Maranguape')],
            284 => [ 'comarca_id' => 8,'nome' => '1ª Vara Cível de Maranguape', 'key' => bcrypt('1ª Vara Cível de Maranguape')],
            285 => [ 'comarca_id' => 42,'nome' => '2ª Vara de Mombaça', 'key' => bcrypt('2ª Vara de Mombaça')],
            286 => [ 'comarca_id' => 4,'nome' => '2ª Vara de Família de Maracanaú', 'key' => bcrypt('2ª Vara de Família de Maracanaú')],
            287 => [ 'comarca_id' => 4,'nome' => '2ª Vara Criminal de Maracanaú', 'key' => bcrypt('2ª Vara Criminal de Maracanaú')],
            288 => [ 'comarca_id' => 49,'nome' => '2ª Vara de Massapê', 'key' => bcrypt('2ª Vara de Massapê')],
            289 => [ 'comarca_id' => 27,'nome' => '1ª Vara Cível de Morada Nova', 'key' => bcrypt('1ª Vara Cível de Morada Nova')],
            290 => [ 'comarca_id' => 4,'nome' => '2ª Vara Cível de Maracanaú', 'key' => bcrypt('2ª Vara Cível de Maracanaú')],
            291 => [ 'comarca_id' => 8,'nome' => '2ª Vara Cível de Maranguape', 'key' => bcrypt('2ª Vara Cível de Maranguape')],
            292 => [ 'comarca_id' => 27,'nome' => '2ª Vara Cível de Morada Nova', 'key' => bcrypt('2ª Vara Cível de Morada Nova')],
            293 => [ 'comarca_id' => 4,'nome' => '3ª Vara Cível – Maracanaú', 'key' => bcrypt('3ª Vara Cível – Maracanaú')],
            294 => [ 'comarca_id' => 4,'nome' => '3ª Vara Criminal – Maracanaú', 'key' => bcrypt('3ª Vara Criminal – Maracanaú')],
            295 => [ 'comarca_id' => 54,'nome' => 'Vara Única de Missão Velha', 'key' => bcrypt('Vara Única de Missão Velha')],
            296 => [ 'comarca_id' => 90,'nome' => 'Vara Única de Morrinhos', 'key' => bcrypt('Vara Única de Morrinhos')],
            297 => [ 'comarca_id' => 70,'nome' => 'Vara Única – Milagres', 'key' => bcrypt('Vara Única – Milagres')],
            298 => [ 'comarca_id' => 68,'nome' => 'Vara Única de Marco', 'key' => bcrypt('Vara Única de Marco')],
            299 => [ 'comarca_id' => 158,'nome' => 'Vara Única de Martinópole', 'key' => bcrypt('Vara Única de Martinópole')],
            300 => [ 'comarca_id' => 161,'nome' => 'Vara Única de Mulungu', 'key' => bcrypt('Vara Única de Mulungu')],
            301 => [ 'comarca_id' => 141,'nome' => 'Vara Única de Miraíma', 'key' => bcrypt('Vara Única de Miraíma')],
            302 => [ 'comarca_id' => 4,'nome' => 'Vara Única da Infância e Juventude de Maracanaú', 'key' => bcrypt('Vara Única da Infância e Juventude de Maracanaú')],
            303 => [ 'comarca_id' => 131,'nome' => 'Vara Única de Meruoca', 'key' => bcrypt('Vara Única de Meruoca')],
            304 => [ 'comarca_id' => 121,'nome' => 'Vara Única de Monsenhor Tabosa', 'key' => bcrypt('Vara Única de Monsenhor Tabosa')],
            305 => [ 'comarca_id' => 39,'nome' => 'Vara Única de Mauriti', 'key' => bcrypt('Vara Única de Mauriti')],
            306 => [ 'comarca_id' => 104,'nome' => 'Vara Única de Madalena', 'key' => bcrypt('Vara Única de Madalena')],
            307 => [ 'comarca_id' => 136,'nome' => 'Vara Única de Mucambo', 'key' => bcrypt('Vara Única de Mucambo')],
            308 => [ 'comarca_id' => 161,'nome' => 'Vara Única de Mulungu', 'key' => bcrypt('Vara Única de Mulungu')],
            309 => [ 'comarca_id' => 62,'nome' => '1ª Vara de Nova Russas', 'key' => bcrypt('1ª Vara de Nova Russas')],
            310 => [ 'comarca_id' => 62,'nome' => '2ª Vara de Nova Russas', 'key' => bcrypt('2ª Vara de Nova Russas')],
            311 => [ 'comarca_id' => 129,'nome' => 'Vara Única de Nova Olinda', 'key' => bcrypt('Vara Única de Nova Olinda')],
            312 => [ 'comarca_id' => 67,'nome' => 'Vara Única de Novo Oriente', 'key' => bcrypt('Vara Única de Novo Oriente')],
            313 => [ 'comarca_id' => 96,'nome' => 'Vara Única de Orós', 'key' => bcrypt('Vara Única de Orós')],
            314 => [ 'comarca_id' => 77,'nome' => 'Vara Única de Ocara', 'key' => bcrypt('Vara Única de Ocara')],
            315 => [ 'comarca_id' => 12,'nome' => '1ª Vara de Pacatuba', 'key' => bcrypt('1ª Vara de Pacatuba')],
            316 => [ 'comarca_id' => 20,'nome' => '1ª Vara de Pacajus', 'key' => bcrypt('1ª Vara de Pacajus')],
            317 => [ 'comarca_id' => 12,'nome' => '2ª Vara de Pacatuba', 'key' => bcrypt('2ª Vara de Pacatuba')],
            318 => [ 'comarca_id' => 20,'nome' => '2ª Vara de Pacajus', 'key' => bcrypt('2ª Vara de Pacajus')],
            319 => [ 'comarca_id' => 150,'nome' => 'Vara Única de Poranga', 'key' => bcrypt('Vara Única de Poranga')],
            320 => [ 'comarca_id' => 55,'nome' => 'Vara Única de Paracuru', 'key' => bcrypt('Vara Única de Paracuru')],
            321 => [ 'comarca_id' => 181,'nome' => 'Vara Única de Potiretama', 'key' => bcrypt('Vara Única de Potiretama')],
            322 => [ 'comarca_id' => 151,'nome' => 'Vara Única de Pacoti', 'key' => bcrypt('Vara Única de Pacoti')],
            323 => [ 'comarca_id' => 52,'nome' => 'Vara Única de Pentecoste', 'key' => bcrypt('Vara Única de Pentecoste')],
            324 => [ 'comarca_id' => 44,'nome' => 'Vara Única de Pedra Branca', 'key' => bcrypt('Vara Única de Pedra Branca')],
            325 => [ 'comarca_id' => 126,'nome' => 'Vara Única de Pereiro', 'key' => bcrypt('Vara Única de Pereiro')],
            326 => [ 'comarca_id' => 122,'nome' => 'Vara Única de Piquet Carneiro', 'key' => bcrypt('Vara Única de Piquet Carneiro')],
            327 => [ 'comarca_id' => 135,'nome' => 'Vara Única de Porteiras', 'key' => bcrypt('Vara Única de Porteiras')],
            328 => [ 'comarca_id' => 99,'nome' => 'Vara Única de Pindoretama', 'key' => bcrypt('Vara Única de Pindoretama')],
            329 => [ 'comarca_id' => 10,'nome' => 'Vara Única Criminal de Quixadá', 'key' => bcrypt('Vara Única Criminal de Quixadá')],
            330 => [ 'comarca_id' => 13,'nome' => '1ª Vara de Quixeramobim', 'key' => bcrypt('1ª Vara de Quixeramobim')],
            331 => [ 'comarca_id' => 13,'nome' => '2ª Vara de Quixeramobim', 'key' => bcrypt('2ª Vara de Quixeramobim')],
            332 => [ 'comarca_id' => 10,'nome' => '1ª Vara Cível de Quixadá', 'key' => bcrypt('1ª Vara Cível de Quixadá')],
            333 => [ 'comarca_id' => 10,'nome' => '2ª Vara Cível de Quixadá', 'key' => bcrypt('2ª Vara Cível de Quixadá')],
            334 => [ 'comarca_id' => 127,'nome' => 'Vara Única de Quixelô', 'key' => bcrypt('Vara Única de Quixelô')],
            335 => [ 'comarca_id' => 15,'nome' => 'Vara Única Criminal de Russas', 'key' => bcrypt('Vara Única Criminal de Russas')],
            336 => [ 'comarca_id' => 15,'nome' => '1ª Vara Cível de Russas', 'key' => bcrypt('1ª Vara Cível de Russas')],
            337 => [ 'comarca_id' => 15,'nome' => '2ª Vara Cível de Russas', 'key' => bcrypt('2ª Vara Cível de Russas')],
            338 => [ 'comarca_id' => 5,'nome' => '1ª Vara Criminal de Sobral', 'key' => bcrypt('1ª Vara Criminal de Sobral')],
            339 => [ 'comarca_id' => 5,'nome' => '1ª Vara Cível de Sobral', 'key' => bcrypt('1ª Vara Cível de Sobral')],
            340 => [ 'comarca_id' => 5,'nome' => '1ª Vara de Família e Sucessões de Sobral', 'key' => bcrypt('1ª Vara de Família e Sucessões de Sobral')],
            341 => [ 'comarca_id' => 38,'nome' => '1ª Vara de São Gonçalo do Amarante', 'key' => bcrypt('1ª Vara de São Gonçalo do Amarante')],
            342 => [ 'comarca_id' => 38,'nome' => '2ª Vara de São Gonçalo do Amarante', 'key' => bcrypt('2ª Vara de São Gonçalo do Amarante')],
            343 => [ 'comarca_id' => 5,'nome' => '2ª Vara Cível de Sobral', 'key' => bcrypt('2ª Vara Cível de Sobral')],
            344 => [ 'comarca_id' => 43,'nome' => '2ª Vara de Santa Quitéria', 'key' => bcrypt('2ª Vara de Santa Quitéria')],
            345 => [ 'comarca_id' => 5,'nome' => '2ª Vara de Família e Sucessões de Sobral', 'key' => bcrypt('2ª Vara de Família e Sucessões de Sobral')],
            346 => [ 'comarca_id' => 5,'nome' => '2ª Vara Criminal de Sobral', 'key' => bcrypt('2ª Vara Criminal de Sobral')],
            347 => [ 'comarca_id' => 5,'nome' => '3ª Vara Criminal de Sobral', 'key' => bcrypt('3ª Vara Criminal de Sobral')],
            348 => [ 'comarca_id' => 5,'nome' => '3ª Vara Cível de Sobral', 'key' => bcrypt('3ª Vara Cível de Sobral')],
            349 => [ 'comarca_id' => 61,'nome' => 'Vara Única de Santana do Acaraú', 'key' => bcrypt('Vara Única de Santana do Acaraú')],
            350 => [ 'comarca_id' => 130,'nome' => 'Vara Única de Saboeiro', 'key' => bcrypt('Vara Única de Saboeiro')],
            351 => [ 'comarca_id' => 147,'nome' => 'Vara Vinculada de São Luís do Curu', 'key' => bcrypt('Vara Vinculada de São Luís do Curu')],
            352 => [ 'comarca_id' => 79,'nome' => '1ª Vara de Senador Pompeu', 'key' => bcrypt('1ª Vara de Senador Pompeu')],
            353 => [ 'comarca_id' => 79,'nome' => '2ª Vara de Senador Pompeu', 'key' => bcrypt('2ª Vara de Senador Pompeu')],
            354 => [ 'comarca_id' => 112,'nome' => 'Vara Única de Solonópole', 'key' => bcrypt('Vara Única de Solonópole')],
            355 => [ 'comarca_id' => 119,'nome' => 'Vara Única de Santana do Cariri', 'key' => bcrypt('Vara Única de Santana do Cariri')],
            356 => [ 'comarca_id' => 5,'nome' => 'Vara Única Da Infância e Juventude de Sobral', 'key' => bcrypt('Vara Única Da Infância e Juventude de Sobral')],
            357 => [ 'comarca_id' => 17,'nome' => 'Vara Única Criminal de Tianguá', 'key' => bcrypt('Vara Única Criminal de Tianguá')],
            358 => [ 'comarca_id' => 29,'nome' => 'Vara Única Criminal de Tauá', 'key' => bcrypt('Vara Única Criminal de Tauá')],
            359 => [ 'comarca_id' => 29,'nome' => '1ª Vara Cível de Tauá', 'key' => bcrypt('1ª Vara Cível de Tauá')],
            360 => [ 'comarca_id' => 17,'nome' => '1ª Vara Cível de Tianguá', 'key' => bcrypt('1ª Vara Cível de Tianguá')],
            361 => [ 'comarca_id' => 29,'nome' => '2ª Vara Cível de Tauá', 'key' => bcrypt('2ª Vara Cível de Tauá')],
            362 => [ 'comarca_id' => 17,'nome' => '2ª Vara Cível de Tianguá', 'key' => bcrypt('2ª Vara Cível de Tianguá')],
            363 => [ 'comarca_id' => 75,'nome' => 'Vara Única de Tamboril', 'key' => bcrypt('Vara Única de Tamboril')],
            364 => [ 'comarca_id' => 30,'nome' => 'Vara Única de Trairi', 'key' => bcrypt('Vara Única de Trairi')],
            365 => [ 'comarca_id' => 56,'nome' => 'Vara Única de Ubajara', 'key' => bcrypt('Vara Única de Ubajara')],
            366 => [ 'comarca_id' => 106,'nome' => 'Vara Única de Umirim', 'key' => bcrypt('Vara Única de Umirim')],
            367 => [ 'comarca_id' => 93,'nome' => 'Vara Única de Uruburetama', 'key' => bcrypt('Vara Única de Uruburetama')],
            368 => [ 'comarca_id' => 140,'nome' => 'Vara Única de Uruoca', 'key' => bcrypt('Vara Única de Uruoca')],
            369 => [ 'comarca_id' => 47,'nome' => 'Vara Única de Várzea Alegre', 'key' => bcrypt('Vara Única de Várzea Alegre')],
            370 => [ 'comarca_id' => 25,'nome' => 'Vara Única de Viçosa do Ceará', 'key' => bcrypt('Vara Única de Viçosa do Ceará')],
            371 => [ 'comarca_id' => 110,'nome' => 'Vara Única de Varjota', 'key' => bcrypt('Vara Única de Varjota')],
            

        ];
        DB::table('varas')->insert($init);
    }
}
